//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class maocoConnEntities : DbContext
    {
        public maocoConnEntities()
            : base("name=maocoConnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Edu_Category> Edu_Category { get; set; }
        public virtual DbSet<Edu_Prod> Edu_Prod { get; set; }
        public virtual DbSet<Edu_Saled_Prod> Edu_Saled_Prod { get; set; }
        public virtual DbSet<Tech_Category> Tech_Category { get; set; }
        public virtual DbSet<Tech_Prod> Tech_Prod { get; set; }
        public virtual DbSet<Tech_Saled_Prod> Tech_Saled_Prod { get; set; }
        public virtual DbSet<Text_Category> Text_Category { get; set; }
        public virtual DbSet<Text_Prod> Text_Prod { get; set; }
        public virtual DbSet<Text_Saled_Prod> Text_Saled_Prod { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
