//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text_Prod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Text_Prod()
        {
            this.Text_Saled_Prod = new HashSet<Text_Saled_Prod>();
        }
    
        public int Id { get; set; }
        public string Prod_Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int Stok { get; set; }
        public int Category_Id { get; set; }
        public string Image { get; set; }
    
        public virtual Text_Category Text_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Text_Saled_Prod> Text_Saled_Prod { get; set; }
    }
}
